name: "Test setup action"
on:
  pull_request:
  workflow_dispatch:

jobs:
  actions:
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [ ubuntu-latest, macos-latest, windows-latest ]
    steps:
      - uses: actions/checkout@v3
      - name: test setup script
        shell: bash
        run: |
          setup/setup_snyk.sh latest ${{ matrix.os }}
          snyk -v
